export const actions = {
  FETCH_ALL: 'FETCH_ALL',
  ADD: 'ADD_BLOG',
  UPDATE: 'EDIT_BLOG',
  DELETE: 'DELETE_BLOG',
  SEARCH: 'SEARCH_BLOG',
  USERLOGIN: 'USER_LOGIN',
  ERROR_LOGIN: 'ERROR_LOGIN',
  SUCCESS_LOGIN: 'SUCCESS_LOGIN',
  RESET_STATUS: 'RESET_STATUS',
  USER_LOGOUT: 'USER_LOGOUT',
};
